version: '3'
services:
  php:
    image: fatindeed/vscode-remote-php
    # ports:
    # - "8080:80"
    volumes:
    - ..:/workspace
    - ${HOME}/.gitconfig:/root/.gitconfig
    - ${HOME}/.ssh:/root/.ssh
  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      DATA_DIR: "/data"
      # ADMINER_PLUGINS: "login-password-less"
    volumes:
      - ../src/database:/data
      - ../adminer-plugins:/var/www/html/plugins-enabled
